/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WatchlistsRouteImport } from './routes/watchlists'
import { Route as StocksSymbolRouteImport } from './routes/stocks/$symbol'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistsRoute = WatchlistsRouteImport.update({
  id: '/watchlists',
  path: '/watchlists',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksSymbolRoute = StocksSymbolRouteImport.update({
  id: '/stocks/$symbol',
  path: '/stocks/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/settings': typeof SettingsRoute
  '/watchlists': typeof WatchlistsRoute
  '/stocks/$symbol': typeof StocksSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/settings': typeof SettingsRoute
  '/watchlists': typeof WatchlistsRoute
  '/stocks/$symbol': typeof StocksSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/settings': typeof SettingsRoute
  '/watchlists': typeof WatchlistsRoute
  '/stocks/$symbol': typeof StocksSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/settings' | '/watchlists' | '/stocks/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/settings' | '/watchlists' | '/stocks/$symbol'
  id:
    '__root__' | '/' | '/auth' | '/settings' | '/watchlists' | '/stocks/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  SettingsRoute: typeof SettingsRoute
  WatchlistsRoute: typeof WatchlistsRoute
  StocksSymbolRoute: typeof StocksSymbolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlists': {
      id: '/watchlists'
      path: '/watchlists'
      fullPath: '/watchlists'
      preLoaderRoute: typeof WatchlistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks/$symbol': {
      id: '/stocks/$symbol'
      path: '/stocks/$symbol'
      fullPath: '/stocks/$symbol'
      preLoaderRoute: typeof StocksSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  SettingsRoute: SettingsRoute,
  WatchlistsRoute: WatchlistsRoute,
  StocksSymbolRoute: StocksSymbolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
